// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: xpdf_service.proto

package xpdfpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PdfToText_GetExtractedText_FullMethodName = "/xpdf.PdfToText/GetExtractedText"
)

// PdfToTextClient is the client API for PdfToText service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PdfToTextClient interface {
	GetExtractedText(ctx context.Context, in *GetExtractedTextRequest, opts ...grpc.CallOption) (*GetExtractedTextResponse, error)
}

type pdfToTextClient struct {
	cc grpc.ClientConnInterface
}

func NewPdfToTextClient(cc grpc.ClientConnInterface) PdfToTextClient {
	return &pdfToTextClient{cc}
}

func (c *pdfToTextClient) GetExtractedText(ctx context.Context, in *GetExtractedTextRequest, opts ...grpc.CallOption) (*GetExtractedTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExtractedTextResponse)
	err := c.cc.Invoke(ctx, PdfToText_GetExtractedText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PdfToTextServer is the server API for PdfToText service.
// All implementations must embed UnimplementedPdfToTextServer
// for forward compatibility.
type PdfToTextServer interface {
	GetExtractedText(context.Context, *GetExtractedTextRequest) (*GetExtractedTextResponse, error)
	mustEmbedUnimplementedPdfToTextServer()
}

// UnimplementedPdfToTextServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPdfToTextServer struct{}

func (UnimplementedPdfToTextServer) GetExtractedText(context.Context, *GetExtractedTextRequest) (*GetExtractedTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExtractedText not implemented")
}
func (UnimplementedPdfToTextServer) mustEmbedUnimplementedPdfToTextServer() {}
func (UnimplementedPdfToTextServer) testEmbeddedByValue()                   {}

// UnsafePdfToTextServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PdfToTextServer will
// result in compilation errors.
type UnsafePdfToTextServer interface {
	mustEmbedUnimplementedPdfToTextServer()
}

func RegisterPdfToTextServer(s grpc.ServiceRegistrar, srv PdfToTextServer) {
	// If the following call pancis, it indicates UnimplementedPdfToTextServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PdfToText_ServiceDesc, srv)
}

func _PdfToText_GetExtractedText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExtractedTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdfToTextServer).GetExtractedText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PdfToText_GetExtractedText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdfToTextServer).GetExtractedText(ctx, req.(*GetExtractedTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PdfToText_ServiceDesc is the grpc.ServiceDesc for PdfToText service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PdfToText_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xpdf.PdfToText",
	HandlerType: (*PdfToTextServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExtractedText",
			Handler:    _PdfToText_GetExtractedText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xpdf_service.proto",
}
